# Generated by Django 5.1.7 on 2025-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
