# Generated by Django 5.1.7 on 2025-05-29 04:03

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinformation',
            fields=[
                ('user_id', models.CharField(default=polls.models.generate_user_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_information',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
