# Generated by Django 5.1.7 on 2025-07-17 09:57

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userinformation_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('task_id', models.CharField(default=polls.models.generate_user_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='任务备注')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('interval_seconds', models.IntegerField(verbose_name='采集间隔(秒)')),
                ('total_duration_minutes', models.IntegerField(verbose_name='总时长(分钟)')),
                ('sample_rate', models.IntegerField(verbose_name='采样率(Hz)')),
                ('points_per_acquisition', models.IntegerField(verbose_name='单次采集点数')),
                ('enabled_channels', models.JSONField(verbose_name='启用的通道列表')),
                ('channel_configs', models.JSONField(verbose_name='通道配置信息')),
                ('csv_file_path', models.CharField(max_length=500, verbose_name='CSV文件路径')),
                ('data_file_size', models.BigIntegerField(default=0, verbose_name='数据文件大小(字节)')),
                ('total_acquisitions', models.IntegerField(default=0, verbose_name='总采集次数')),
                ('total_data_points', models.BigIntegerField(default=0, verbose_name='总数据点数')),
                ('user_email', models.CharField(max_length=100, verbose_name='用户邮箱')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '监控任务',
                'verbose_name_plural': '监控任务',
                'db_table': 'monitor_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
