# Generated by Django 5.1.7 on 2025-07-22 07:02

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_monitortask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('training_set_id', models.CharField(default=polls.models.generate_user_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='训练集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='训练集描述')),
                ('start_time', models.DateTimeField(verbose_name='训练开始时间')),
                ('model_type', models.CharField(max_length=50, verbose_name='模型类型')),
                ('training_mode', models.CharField(max_length=20, verbose_name='训练模式')),
                ('selected_data_sources', models.JSONField(verbose_name='选中的数据源')),
                ('learning_params', models.JSONField(verbose_name='学习参数配置')),
                ('user_email', models.CharField(max_length=100, verbose_name='用户邮箱')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(default='created', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '训练集',
                'verbose_name_plural': '训练集',
                'db_table': 'training_sets',
                'ordering': ['-created_at'],
            },
        ),
    ]
