# Generated by Django 5.1.7 on 2025-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_trainingset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='current_epoch',
            field=models.IntegerField(default=0, verbose_name='当前训练轮数'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='是否暂停'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='pause_requested',
            field=models.BooleanField(default=False, verbose_name='是否请求暂停'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='total_epochs',
            field=models.IntegerField(default=0, verbose_name='总训练轮数'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='training_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='训练状态'),
        ),
    ]
