# Generated by Django 5.1.7 on 2025-07-25 12:33

import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_trainingset_current_epoch_trainingset_is_paused_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedModel',
            fields=[
                ('model_id', models.CharField(default=polls.models.generate_user_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('model_type', models.CharField(max_length=50, verbose_name='模型类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('model_file_path', models.CharField(max_length=500, verbose_name='模型文件路径')),
                ('model_file_size', models.BigIntegerField(default=0, verbose_name='模型文件大小(字节)')),
                ('training_set_name', models.CharField(max_length=200, verbose_name='训练集名称')),
                ('final_training_loss', models.FloatField(blank=True, null=True, verbose_name='最终训练损失')),
                ('final_validation_loss', models.FloatField(blank=True, null=True, verbose_name='最终验证损失')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='准确率')),
                ('model_params', models.JSONField(verbose_name='模型参数')),
                ('user_email', models.CharField(max_length=100, verbose_name='用户邮箱')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deployed', models.BooleanField(default=False, verbose_name='是否已部署')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('training_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.trainingset', verbose_name='关联训练集')),
            ],
            options={
                'verbose_name': '已保存模型',
                'verbose_name_plural': '已保存模型',
                'db_table': 'saved_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
